myList = [1,2,3,4,5,6,7,8,9]
print("The original List")
print(myList)
print("Inserting an element in the List at position 3")
myList.insert(3, 100)
print(myList)
print("Remove an element in the List")
myList.remove(1)
print(myList)
print("Appending an element in the List")
myList.append(10)
print(myList)
print("Pop an element in the List")
myList.pop(2)
print(myList)
print("Reverse an element in the List")
myList.reverse()
print(myList)
print("sort an element in the List")
myList.sort()
print(myList)
